spring:
  application:
    name: subscriptions
  datasource:
    url: ${DB_URL:jdbc:mysql://cyna_db:3306/cyna_db}
    username: ${DB_USERNAME:cyna_user}
    password: ${DB_PASSWORD:cyna_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

server:
  port: ${PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${URL_EUREKA:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${HOST_SUBSCRIPTIONS:${spring.application.name}}
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: false
    securePortEnabled: false
    nonSecurePortEnabled: true
    nonSecurePort: ${PORT:8083}


logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:warn}
    web: ${LOGGING_LEVEL_WEB:warn}
  file:
    name: ./target/cyna-orders.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

stripe:
  STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
  STRIPE_API_VERSION: ${STRIPE_API_VERSION}
  return_url: ${STRIPE_RETURN_URL:http://localhost:1234}

mailerSend:
  from: ${MAIL_USERNAME:wilfried@trial-ywj2lpnqzo1g7oqz.mlsender.net}
  support_email: ${SUPPORT_MAIL:wilfried@trial-ywj2lpnqzo1g7oqz.mlsender.net}
  token: ${API_TOKEN}
  templates:
    generic_template: ${TEMPLATE_GENERIC:3z0vklo86e147qrx}
    generic_template_with_button: ${TEMPLATE_GENERIC_WITH_BUTTON:jpzkmgq87o2g059v}
    email_verified: ${TEMPLATE_EMAIL_VERIFIED:jy7zpl998erl5vx6}


